### ISSUE TITLE
Issue with system/proxy/password value in settings table

### ISSUE THREAD

**Issue by milleri** [delwp-gn/core-geonetwork#1]
I have now confirmed that this issue is causing the many Geonetwork instance problems we have been experiencing in the past 2-3 weeks.

The error is that the value field for the name 'system/proxy/password' in the settings table is, for some unknown reason, "blowing out" to become extremely large - ~300 MB.  This causes Geonetwork to fail in many ways including Java heap errors and to become unworkably slow where it does not fail outright.
Manually nulling out the value returns the instance to a working state.

I believe this issue may be being triggered by the following issue https://sourceforge.net/p/geonetwork/mailman/message/37325959/
I have observed that the Proxy user name and password fields in the system settings screen are being out populated to the values used to log into Geonetwork, if the user has allowed their browser to save these credentials.  If the user doesn't notice these have been set and remove them before saving, they end up in the settings table.  I don't know why or how the password then ends up blowing out to hundreds of MB.  I suspect it may be related to the new (since 3.4.x) encryption function but I have no evidence of that.

**Comment by sppigot** [comment]
Thanks Ian - this doesn't seem to reproduce on my local machine or VMs at work and am wondering whether this is something specific to AWS (I note that the original report also refers to an AWS instance too). Anyway have committed the autocomplete="off" attribute change to the form that contains the proxy password. I am rather mystified by the proposed fix and a little bit skeptical but let's try it as a first attempt at a fix and delve more deeply if it doesn't work.....

**Comment by sppigot** [comment]
Reproduced and fixed.
Another issue causing slowness was the handling of the clob type field in the system settings table. Changed that to a fixed length varchar type - it no longer needs to be a clob as the settings for the harvester are now held elsewhere. Similarly for the main GeoNetwork config. The system settings table was read 3 or 4 times during the editor save and this was causing a 7 or so second delay in processing saves in the editor (which also occurs on changing tabs).
Another issue was the size of the footprint geometries being held as gml:polygons in rastermeta records. These need to be generalized or handled in some other way as there are too many points in the polygon outlines.
